config/routes.rb
Quora::Application.routes.draw do
  
  resources :homeworks do
    collection do
      post :create_teacher_attachement
    end
    
    member do
      get :download_teacher_zip
    end
  end
  get 'homeworks/:id/:download_teacher_zip' => 'homeworks#download_teacher_zip'
  # 老师查看某一学生作业路由
  get 'homeworks/:homework_id/student/:user_id' => 'homeworks#student'
  
  resources :student do
    collection do
      post :upload_homework_attachement
      post :upload_homework_attachement_again
    end
    
    member do
    end
  end
  resources :homeworks, :student

  # -- 用户登录认证相关 --
  root :to=>"index#index"
  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/logout' => 'sessions#destroy'
  
  get  '/signup'        => 'signup#form'
  post '/signup_submit' => 'signup#form_submit'
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  
  validates :real_name, :presence=>true
  validates :sid, :uniqueness => { :if => Proc.new { |student| !student.sid.blank? } }
  
  module UserMethods
    def self.included(base)
      base.has_one :student
      base.send(:include,InstanceMethod)
    end
    
    module InstanceMethod
      def is_student?
        !self.student.blank?
      end
    end
  end
end

app/controllers/student_controller.rb
require 'zip/zip'
class StudentController < ApplicationController
  def index
    if params[:status] == 'deadline'
      @homeworks = current_user.deadline_student_homeworks
    elsif params[:status] == 'undeadline'
      @homeworks = current_user.undeadline_student_homeworks
    else
      @homeworks = current_user.assigned_homeworks
    end
    
  end

  def show
    @homework = Homework.find(params[:id])
    @student_homework = current_user.homework_assigns.find_by_homework_id(params[:id])
    @homework_assign = HomeworkAssign.new

  end

  def create
    homework = Homework.find(params[:homework_assign][:homework_id])
    return redirect_to :back if homework.submit_by_student(current_user,params[:homework_assign][:content])

    error = @homework_assign.errors.first
	  flash.now[:error] = "#{error[0]} #{error[1]}"
	  render :action => :show
  end
  
  # 学生上传作业附件
  def upload_homework_attachement
    # attachement_id 值由页面ajax url 参数传进来
    params[:homework_student_upload][:attachement_id] = params[:attachement_id]
    params[:homework_student_upload][:creator_id] = current_user.id
    @homework_student_upload = HomeworkStudentUpload.create( params[:homework_student_upload] )

    # 当前作业ID, 用于生成 zip 文件名
    homework_id = @homework_student_upload.homework_student_upload_requirement.homework.id
    homework = Homework.find(homework_id)
    homework.build_student_attachements_zip(current_user, @homework_student_upload)
    
    render :nothing => true
  end
  
  # 学生重新上传作业附件
  def upload_homework_attachement_again
    homework_student_upload_requirement = HomeworkStudentUploadRequirement.find(params[:attachement_id])
    @homework_student_upload = homework_student_upload_requirement.upload_of_user(current_user)
    old_file = @homework_student_upload.attachement_file_name;
    @homework_student_upload.attachement = params[:homework_student_upload][:attachement]
    @homework_student_upload.save
    
    # 当前作业ID, 用于生成 zip 文件名
    homework_id = @homework_student_upload.homework_student_upload_requirement.homework.id
    homework = Homework.find(homework_id)
    homework.build_student_attachements_zip(current_user, @homework_student_upload, old_file)
    
    render :nothing => true
  end

end

app/views/student/index.html.haml
%p
  %a{:href => '/student?status=undeadline'} 未过期
  %a{:href => '/student?status=deadline'} 已过期

- @homeworks.each do |h|
  %p= link_to h.title, student_path(h)
  %p
    截止时间
    =h.deadline.strftime("%Y-%m-%d %H:%M:%S")
  
  - if h.assigned_by_student(current_user).has_finished
    = '我已完成'
  - else
    = '我未完成'
  

app/views/student/show.html.haml
%p= link_to '我的作业列表', '/student'

%div 作业标题
%p= @homework.title

%div 截止时间
%p= @homework.deadline.strftime("%Y-%m-%d %H:%M:%S")

%p
  提交物:
  = @homework.homework_teacher_attachements.count
  要求附件:
  - @homework.homework_teacher_attachements.each do |h|
    = h.attachement_file_name

%div
  %a{:href => "to_do"} Zip包全部下载

%div
  - @homework.homework_student_upload_requirements.each do |h|
    %p= h.title
    - if current_user.is_upload_homework_attachement?(h)
      = '已提交'
      再次上传
      :javascript
        $(function() {
          $("#dropbox_#{h.id}, #multiple_#{h.id}").html5Uploader({
            name: "homework_student_upload[attachement]",
            postUrl: '/student/upload_homework_attachement_again?attachement_id=#{h.id}',
          });
        });
      %div{:id => "dropbox_#{h.id}"}
      %input{:id => "multiple_#{h.id}", :multiple => "", :type => "file", :name => "homework_student_upload[attachement]"}/
      - homework_student_upload = h.upload_of_user(current_user)
      %a{:href => "#{homework_student_upload.attachement.url}"} 下载
    - else
      = '未提交'
      上传
      :javascript
        $(function() {
          $("#dropbox_#{h.id}, #multiple_#{h.id}").html5Uploader({
            name: "homework_student_upload[attachement]",
            postUrl: '/student/upload_homework_attachement?attachement_id=#{h.id}',
          });
        });
      %div{:id => "dropbox_#{h.id}"}
      %input{:id => "multiple_#{h.id}", :multiple => "", :type => "file", :name => "homework_student_upload[attachement]"}/
    
%div
  %a{:href => "to_do"} Zip包全部下载


%div 作业内容
%p= @homework.content


%div 学生提交内容
%p= @student_homework.content

.page-new
  = flash.now[:error]

= form_for @homework_assign, :url => { :action => "create" } do |f|

  %p 作业内容
  = f.hidden_field :homework_id, :value => @homework.id
  = f.text_area :content, :size => "60x12"

  = f.submit "提交作业"