config/routes.rb
Quora::Application.routes.draw do
  
  resources :homeworks do
    collection do
      post :create_teacher_attachement
    end
    
    member do
      get :download_teacher_zip
    end
  end
  get 'homeworks/:id/:download_teacher_zip' => 'homeworks#download_teacher_zip'
  # 老师查看某一学生作业路由
  get 'homeworks/:homework_id/student/:user_id' => 'homeworks#student'
  
  resources :student do
    collection do
      post :upload_homework_attachement
      post :upload_homework_attachement_again
    end
    
    member do
    end
  end
  resources :homeworks, :student

  # -- 用户登录认证相关 --
  root :to=>"index#index"
  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/logout' => 'sessions#destroy'
  
  get  '/signup'        => 'signup#form'
  post '/signup_submit' => 'signup#form_submit'
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  # --- 模型关联
  belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
  has_many :homework_assigns
  has_many :homework_student_upload_requirements
  accepts_nested_attributes_for :homework_student_upload_requirements
  
  # 未提交作业学生
  has_many :unsubmitted_students, :through => :homework_assigns, :source => :creator, :conditions => ['is_submit = ?', false]
  
  # 已提交作业学生
  has_many :submitted_students, :through => :homework_assigns, :source => :creator, :conditions => ['is_submit = ?', true]
  
  # 学生附件
  has_many :homework_student_upload_requirements
  
  # 老师创建作业时上传的附件
  has_many :homework_teacher_attachements
  
  accepts_nested_attributes_for :homework_assigns
  
  # --- 校验方法
  validates :title, :content, :presence => true
  
  def assigned_by_student(user)
    self.homework_assigns.where(:creator_id => user.id).first
  end
  
  # 学生是否被分配
  def is_assigned(creator_id)
    self.homework_assigns.where(:creator_id => creator_id).exists?
  end
  
  
  # 老师创建作业时生成的附件压缩包
  def build_teacher_attachements_zip(user)
    zipfile_name = "/web/2012/homework_teacher_attachements/homework_teacher#{user.id}_#{self.id}.zip"
    Zip::ZipFile.open(zipfile_name, Zip::ZipFile::CREATE) do |zipfile|
      self.homework_teacher_attachements.each do |file|
        unless zipfile.find_entry(file.attachement_file_name)
          zipfile.add(file.attachement_file_name, file.attachement.path)
        end
      end
    end
  end
  
  # 压缩学生提交的附件
  def build_student_attachements_zip(user, homework_student_upload, old_file = '')
    # homework_id = homework_student_upload.homework_student_upload_requirement.homework.id
    homework_id = self.id
    zipfile_name = "/web/2012/homework_student_uploads/homework_student#{user.id}_#{homework_id}.zip"
    Zip::ZipFile.open(zipfile_name, Zip::ZipFile::CREATE) do |zipfile|
      zipfile.remove(old_file) if zipfile.find_entry(old_file) && old_file != ''
      zipfile.add(homework_student_upload.attachement_file_name, homework_student_upload.attachement.path)
    end
  end
  
  # 学生提交作业
  def submit_by_student(user, content = '')
    homework_assign = self.homework_assigns.find_by_creator_id(user.id)
    homework_assign.content = content
    homework_assign.is_submit = true
    homework_assign.has_finished = true
    homework_assign.submitted_at = DateTime.now
    homework_assign.save
  end
  
  # --- 给其他类扩展的方法
  module UserMethods
    def self.included(base)
      base.has_many :homeworks, :foreign_key => :creator_id
      
      # 老师未过期作业
      base.has_many :undeadline_teacher_homeworks, :class_name => 'Homework', :foreign_key => :creator_id, :conditions => ['deadline > ?', Time.new.strftime("%Y-%m-%d %H:%M:%S")]
      
      # 老师已过期作业
      base.has_many :deadline_teacher_homeworks, :class_name => 'Homework', :foreign_key => :creator_id, :conditions => ['deadline <= ?', Time.now]
      
      base.send(:include, InstanceMethods)
    end
    
    module InstanceMethods
      # nothing ...
    end
  end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_filter :pre_load

  def pre_load
    return redirect_to '/' unless current_user.is_teacher?
  end
  
  
  def create
    @homework = current_user.homeworks.build(params[:homework])
    if @homework.save
      teacher_attachements = params[:teacher_attachements]
      unless teacher_attachements.blank?
        teacher_attachements.each do |attachement_id|
          homework_teacher_attachement = HomeworkTeacherAttachement.find(attachement_id)
          homework_teacher_attachement.homework_id = @homework.id
          homework_teacher_attachement.creator_id = current_user.id
          homework_teacher_attachement.save
        end
      end
      
      teams = params[:teams]
      unless teams.blank?
        teams.each do |team_id|
          team = Team.find(team_id)
                   
          team.team_students.each do |student|

            unless @homework.is_assigned(student.student_id)
              homework_assign = HomeworkAssign.new
              homework_assign.creator_id = student.student_id
              homework_assign.homework_id = @homework.id
              homework_assign.created_at = Time.now
              homework_assign.updated_at = Time.now
              homework_assign.save
            end
            
          end
        end
      end
      
      return redirect_to @homework
    end
    
    error = @homework.errors.first
	  flash.now[:error] = "#{error[0]} #{error[1]}"
	  redirect_to '/homeworks/new'
  end
  
  def create_teacher_attachement
    @homework_teacher_attachement = HomeworkTeacherAttachement.create( params[:homework_teacher_attachement] )
    render :text => @homework_teacher_attachement.id
  end
  

  def new
    @homework = Homework.new
    @homework_student_upload_requirement = HomeworkStudentUploadRequirement.new
    
    # 所有课程
    @courses = Course.all
    
    # 班级列表
    @teams = Team.all
    
    # 学生列表
    @students = Student.all
  end

  def index
    if params[:status] == 'deadline'
      @homeworks = current_user.deadline_teacher_homeworks
    elsif params[:status] == 'undeadline'
      @homeworks = current_user.undeadline_teacher_homeworks
    else
      @homeworks = current_user.homeworks
    end
  end
  
  
  def show
    @homework = Homework.find(params[:id])
  end
  
  
  # 老师查看具体某一学生作业页面
  def student
    @homework = Homework.find(params[:homework_id])
    @student = User.find(params[:user_id])
  end
  
  def download_teacher_zip
    homework = Homework.find(params[:id])
    
    # 生成老师上传的附件压缩包
    homework.build_teacher_attachements_zip(homework.creator)
    
    render :file => "/web/2012/homework_teacher_attachements/homework_teacher#{homework.creator.id}_#{homework.id}.zip", :content_type => 'application/zip', :status => :ok
  end

end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/index.html.haml
%p= link_to '布置新作业', new_homework_path

%p
  %a{:href => homeworks_path(:status => 'undeadline')} 未过期
  %a{:href => homeworks_path(:status => 'deadline')} 已过期

- @homeworks.each do |h|
  %p= link_to h.title, homework_path(h)
  %p
    截止时间
    =h.deadline.strftime("%Y-%m-%d %H:%M:%S")

app/views/homeworks/new.html.haml
:javascript
  // 删除班级标签
  function del_team(id) {
    $('#del-a-team' + id).remove();
    
    // 把临时列表保存的插入到班级列表之前
    var team = $('#team-temp-list').html();
    team = team.replace('<div>', '<div id="team-current-' + id + '">');
    $('#confirm-teams').before(team);
    
    // 清空临时班级列表
    $('#team-temp-list').html('');
  }
  
  // 删除学生标签
  function del_student(id) {
    $('#del-a-student' + id).remove();
    
    // 把临时列表保存的插入到班级列表之前
    var student = $('#student-temp-list').html();
    student = student.replace('<div>', '<div id="student-current-' + id + '">');
    $('#confirm-students').before(student);
    
    // 清空临时班级列表
    $('#student-temp-list').html('');
  }
  
  
  jQuery(document).ready(function(){
  
    // 上传老师附件
    jQuery('.multiple').live('click', function(){
      jQuery("#dropbox, .multiple").html5Uploader({
        name: "homework_teacher_attachement[attachement]",
        postUrl: '/homeworks/create_teacher_attachement',
        onSuccess: function(e, file, data){
          // console.log(data);
          var attachements = '<input type="text" name="teacher_attachements[]" value="' + data + '" value="">';
          $('#teacher-attachements').append(attachements);
        }
      });
    })

    
    // 添加学生附件表单
    jQuery('#add-student-attachement-field').click(function(){
      var attachement_field = "<input type='text' size='30' name='homework[homework_student_upload_requirements_attributes][][title]'>";
      var del_field = "<a href='javascript:void(0);' class='delete'>x</a>";
      $('#student-attachement-fields').append("<p>" + attachement_field + del_field + "</p>");
    })
    
    // 删除表单
    jQuery('a.delete').live('click', function(){
      $(this).parent().remove();
    })
    
    // 添加老师附件表单
    jQuery('#add-teacher-attachement-field').click(function(){
      var attachement_field = '<input type="file" name="homework_teacher_attachement[attachement]" multiple="" class="multiple">';
      var del_field = "<a href='javascript:void(0);' class='delete'>x</a>";
      $('#teacher-attachement-fields').append("<p>" + attachement_field + del_field + "</p>");
    })
    
    // 班级列表
    jQuery('#team-by').click(function(){
      // 显示班级列表
      $('#team-list').show();
      
      // 隐藏学生列表
      $('#student-list').hide();
      
    })
    
    
    // 确定选择的班级列表
    jQuery('#confirm-teams').click(function(){
      $('#team-list').hide();
      var selected = new Array();
      $('#team-list input:checked').each(function() {
 
          var value = $(this).attr('value');
          var name = $(this).attr('name');
          
          if($("#del-a-team" + value).length == 0) {
            var delete_name = "<a href='javascript:' onclick='del_team(" + value + ")'>x</a>";
            var input_string = "<span id='del-a-team" + value + "'>" + name + delete_name + 
                               "<input type='hidden' value='" + value + "' name='teams[]' /></span>";
            $('#selected-teams').append(input_string);
          }
          
          // 用于临时存放，如果删除班级标签时，可以随时拿出来
          $('#team-temp-list').append('<div>' + $("#team-current-" + value).html() + '</div>');
          
          $('#team-current-' + value).remove();
      });
      
    })
    
    
    // 学生列表
    jQuery('#student-by').click(function(){
      // 隐藏班级列表
      $('#team-list').hide();
      
      // 显示学生列表
      $('#student-list').show();

    })

    
    // 主要用于重新显示学生列表
    jQuery('#show-students').click(function(){
      // 先隐藏班级
      $('#team-list').hide();
      
      // 学生列表显示出来
      $('#student-list').show();
      
      // 把分类显示出来
      $('#category-by').show();
     
    })
    
    // 确定选择的学生列表
    jQuery('#confirm-students').click(function(){
      $('#student-list').hide();
      var selected = new Array();
      $('#student-list input:checked').each(function() {
          // selected.push($(this).attr('value'));
          
          var value = $(this).attr('value');
          var name = $(this).attr('name');
          
          if($("#del-a-student" + value).length == 0) {
            var delete_name = "<a href='javascript:' onclick='del_student(" + value + ")'>x</a>";
            var input_string = "<span id='del-a-student" + value + "'>" + name + delete_name + "<input type='hidden' value='" + value + "' name='homework[homework_assigns_attributes][][creator_id]' /></span>";
            $('#selected-students').append(input_string);
          }
          
          // 用于临时存放，如果删除学生标签时，可以随时拿出来
          $('#student-temp-list').append('<div>' + $("#student-current-" + value).html() + '</div>');
          
          $('#student-current-' + value).remove();
      });
    })

  });
  

%p= link_to '作业列表', homeworks_path

.page-new
  = flash.now[:error]

= form_for @homework, :url => { :action => "create" }, :html => {:class => "assign_form", :multipart => true} do |f|
  %p 作业标题
  = f.text_field :title
  
  %p 作业内容
  = f.text_area :content, :size => "60x12"
  
  %p 隶属课程
  = f.select :course_id, @courses.collect {|item| [item.name, item.id]}
  
  %p 截止日期
  = f.text_field :deadline
  
  %p 
    选择分配学生
    %a#show-students{:href => "javascript:void(0);"} +
  
  %p
    #selected-teams
    #selected-students 
  
  %p#category-by{:style => "display: none;"}
    %span#team-by 按班级 
    %span#student-by 按学生
  
  #team-temp-list{:style => "display: none;"}
  #team-list{:style => "display: none;"}
    -@teams.each do |team|
      %div{:id => "team-current-#{team.id}"}
        %input{:type=>'checkbox', :value => "#{team.id}", :name=>"#{team.name}"} 
        #{team.name} (#{team.team_students.count})
        
    %input#confirm-teams{:name => "confirm_btn", :type => "button", :value => "确定"}/
  
  #student-temp-list{:style => "display: none;"}
  #student-list{:style => "display: none;"}
    -@students.each do |student|
      %div{:id => "student-current-#{student.user_id}"}
        %input{:type=>'checkbox', :value => student.user_id, :name=>"#{student.real_name}"} 
        #{student.real_name}
    
    %input#confirm-students{:name => "confirm_btn", :type => "button", :value => "确定"}/
  
  
  
  %p 
    老师作业附件
    #teacher-attachements{:style => "display: none;"}
    %a#add-teacher-attachement-field{:href => "javascript:"} 添加+
    #dropbox
    %div{:id => "teacher-attachement-fields"}
      %input.multiple{:multiple => "", :type => "file", :name => "homework_teacher_attachement[attachement]"}/
    
  %div
    学生作业提交物
    %a#add-student-attachement-field{:href => "javascript:"} 添加+
    
    %div{:id => "student-attachement-fields"}
      %p
        %input{:type=>'text', :size=>30, :name=>'homework[homework_student_upload_requirements_attributes][][title]'}
        %a.delete{:href => "javascript:void(0);"} x
      %p
        %input{:type=>'text', :size=>30, :name=>'homework[homework_student_upload_requirements_attributes][][title]'}
        %a.delete{:href => "javascript:void(0);"} x
    
  = f.submit "布置作业"
  


     

app/views/homeworks/show.html.haml
:ruby
  student_attachements_count = @homework.homework_student_upload_requirements.count

%p= link_to '作业列表', homeworks_path
%p= link_to '布置新作业', new_homework_path

%div 作业标题
%p= @homework.title

%div 作业内容
%p= @homework.content

%div 截止时间
%p
  = @homework.deadline.strftime("%Y-%m-%d %H:%M:%S")
  - if Time.now < @homework.deadline
    = '未过期'
  - else
    = '已过期'

%div 
  提交物
  = student_attachements_count
  - @homework.homework_teacher_attachements.each do |attachement|
    = attachement.attachement_file_name
  %div
    %a{:href => "/homeworks/#{@homework.id}/download_teacher_zip"} Zip包全部下载



%div
  - @homework.homework_assigns.each do |h|
    - uploaded_count = h.user.uploaded_count_of_student_homework(@homework)
    %p
      %a{:href => "/homeworks/#{h.homework_id}/student/#{h.user.id}"} 
        =h.user.name
    = uploaded_count
    %span /
    = student_attachements_count
    
    - if uploaded_count == student_attachements_count
      %span 完成
    - else
      %span 未完成
      
    - if h.has_finished
      %span 已签
    - else 
      %span 未签

app/views/homeworks/student.html.haml
:ruby
  # 学生应该提交的附件数量
  student_attachements_count = @homework.homework_student_upload_requirements.count
  
  # 学生已经提交的附件数量
  uploaded_count = @student.uploaded_count_of_student_homework(@homework)
  
  
%div 作业标题
%p= @homework.title

%div 作业内容
%p= @homework.content

%p
  = @student.name
  = uploaded_count.to_s + "/" + student_attachements_count.to_s
  - if uploaded_count == student_attachements_count
    %span 完成
  - else
    %span 未完成
    
%div
  提交物情况
  - @homework.homework_student_upload_requirements.each do |attachement|
    %p
      = attachement.title
      - if @student.is_upload_homework_attachement?(attachement)
        - current_upload = attachement.upload_of_user(@student)
        %span 已提交
        %a{:href => "#{current_upload.attachement.url}"} 下载
      - else
        %span 未提交
        
%p
  %a{:href => ""} 以zip下载